apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    app: myapp
    env: devops
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
        env: devops
    spec:
      containers:
        - name: myapp
          image: nginx
          ports:
            - containerPort: 80
        - name: myapp
          image: nginx
          ports:
            - containerPort: 80
