apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-ss
  labels:
    app: my-app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app2
  template:
    metadata:
      name: my-pod2
      labels:
        app: my-app2
        env: devops
    spec:
      containers:
        - name: mariadb
          image: mariadb
          ports:
          - name: db
            containerPort: 3306
          env:
          - name: MARIADB_ROOT_PASSWORD
            value: admin123
...
---
apiVersion: v1
kind: Service
metadata:
  name: my-svc-node
  labels:
    app: my-svc-node
    env: devops
spec:
  type: NodePort
  selector:
    app: my-app2
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
