apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  labels:
    app: mariadb
spec:
  ports:
  - port: 3306
    name: mariadb-port
  selector:
    app: mariadb

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mystatefulset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mariadb
  serviceName: "mariadb"
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb
        ports:
        - containerPort: 3306
          name: student
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin123

  